会場を株式会社インプレスに変更した
kawa-souta/ichiyasaGitSample pull request #1
Opened 2022-07-03 08:32 UTC by kawa-souta

### 変更内容
イベント

2022-07-03 08:47 UTC, kawa-mayumi commented
修正ありがとう

2022-07-03 08:47 UTC, kawa-mayumi commented
マージしてもよい

2022-07-03 09:02 UTC, kawa-mayumi requested changes
Leave

2022-07-03 09:02 UTC, kawa-mayumi commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
していただけますか

2022-07-09 07:26 UTC, closed without merging

2022-07-09 09:45 UTC, kawa-souta commented
tst